DECLARE Height_HF_VERSION_ENFORCE_MIN_AGE INT = 1978433;
DECLARE CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE INT = 10;

SELECT
	COUNT(1)
FROM txo_first_ring
WHERE ring_height >= Height_HF_VERSION_ENFORCE_MIN_AGE
	AND ring_height - txo_height < CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE;